services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ecommerce-network

  frontend:
    build:
      context: ./aplication-consumo-ecommerce
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge